name: LADWP Auto Update
on:
  schedule:
    - cron: '0 10 1 * *' 
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        run: python update_rates.py

      - name: Commit and Push Changes
        # This only runs if the scraper was successful
        run: |
          git config --global user.name 'LADWP-Bot'
          git config --global user.email 'bot@utilityestimator.com'
          git add ladwp_rates.json
          git commit -m "Automated rate update: $(date)" || exit 0
          git push
